name: smart_parent_assistant
description: Smart Parent Assistant – Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ COMPATIBLE with latest Flutter
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo/app_logo.png
    - assets/ml/child_reason.tflite
    - assets/ml/labels.txt

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo/app_logo.png"